### ISSUE TITLE
Patcher thinks my game files are outdated despite it already being updated via other sources.

### ISSUE THREAD

**Issue by Aorimiku** [Yen/PSRT.Astra#16]
Trying to use the patcher with an already updated version of PSO2 forces it to queue 71k files to download because they are "outdated" [(screenshot)](https://i.imgur.com/zxmaBb6.jpg).

An option to force the patcher to skip the file check and label the current files as "updated" would solve the issue.

This is my first time submitting an issue here so sorry if I'm doing something wrong.

**Comment by Yen** [comment]
Hey, thanks for the issue.

Astra is not actually downloading files here. I think I need to change the wording here but Astra is just calculating the hashes of the files to check them compared to what _should_ be there. Only files that are _actually_ outdated ever get downloaded.

I hesitate do change this behaviour as its the only real way I can be sure that Astra can keep your game in a non corrupted state, the application trusts these calculations fully.

Changing the wording from "updating" is something I am up for if someone can propose a wording that can be used in the case for both scanning like you have here, but for also when you are actually updating the game. At this time I don't know of any way for Astra to tell these two operations apart because they are actually the same thing, so a word that can be used for both would be required.

**Comment by Yen** [comment]
Yeah, because we are now skipping the selection of the installation when the user restarts the application with a saved install path, I am considering showing a message box when the user selects a install location period. Just a little something that explains what its doing. In practice most users should only see this once and if they do see it again because they changed where they want their PSO2 install to live, its just a message box.

Gonna leave this open until I get round to that or someone else has a better idea.

**Comment by Yen** [comment]
Fixed by ce1b5032a12b21237b90b139130aba061eff7ebe
